use std::{iter::FusedIterator, str::Chars};

const EMPTY: u16 = 0;
const IDENTITY: u16 = 1;
const FIRST_ENTRY: u16 = 2;

// Hangul syllable decomposition constants (Unicode ch. 3.12).
const S_BASE: u32 = 0xAC00;
const S_COUNT: u32 = 11172;
const L_BASE: u32 = 0x1100;
const V_BASE: u32 = 0x1161;
const T_BASE: u32 = 0x11A7;
const T_COUNT: u32 = 28;
const N_COUNT: u32 = 588;

/// Two-level lookup table generated by `build.rs`.
pub(super) struct Table {
    pub level1: &'static [u16; 0x1100],
    pub blocks: &'static [u16],
    pub entries: &'static [u32],
    pub pool: &'static str,
}

impl Table {
    #[inline]
    pub(super) fn lookup(&self, c: char) -> MappedChar {
        let cp = c as u32;

        if let Some(s) = cp.checked_sub(S_BASE).filter(|&s| s < S_COUNT) {
            return MappedChar::hangul(s);
        }

        let cp = cp as usize;
        let block = self.level1[cp >> 8] as usize;

        match self.blocks[(block << 8) | (cp & 0xFF)] {
            EMPTY => MappedChar::single(None),
            IDENTITY => MappedChar::single(Some(c)),
            id => {
                let packed = self.entries[(id - FIRST_ENTRY) as usize];
                let offset = (packed >> 8) as usize;
                let len = (packed & 0xFF) as usize;

                MappedChar(Repr::Pool(self.pool[offset..offset + len].chars()))
            }
        }
    }
}

/// Iterator over the chars a single char maps to.
#[derive(Clone, Debug)]
pub struct MappedChar(Repr);

#[derive(Clone, Debug)]
enum Repr {
    Inline { buf: [char; 3], pos: u8, len: u8 },
    Pool(Chars<'static>),
}

impl MappedChar {
    #[inline]
    pub(super) fn single(c: Option<char>) -> Self {
        Self(Repr::Inline {
            buf: [c.unwrap_or('\0'); 3],
            pos: 0,
            len: c.is_some() as u8,
        })
    }

    #[inline]
    fn hangul(s: u32) -> Self {
        let l = L_BASE + s / N_COUNT;
        let v = V_BASE + (s % N_COUNT) / T_COUNT;
        let t = s % T_COUNT;

        Self(Repr::Inline {
            buf: [
                char::from_u32(l).unwrap(),
                char::from_u32(v).unwrap(),
                char::from_u32(T_BASE + t).unwrap(),
            ],
            pos: 0,
            len: 2 + (t != 0) as u8,
        })
    }
}

impl Iterator for MappedChar {
    type Item = char;

    #[inline]
    fn next(&mut self) -> Option<char> {
        match &mut self.0 {
            Repr::Inline { buf, pos, len } => {
                if pos < len {
                    let c = buf[*pos as usize];
                    *pos += 1;
                    Some(c)
                } else {
                    None
                }
            }
            Repr::Pool(chars) => chars.next(),
        }
    }

    #[inline]
    fn size_hint(&self) -> (usize, Option<usize>) {
        match &self.0 {
            Repr::Inline { pos, len, .. } => {
                let n = (len - pos) as usize;
                (n, Some(n))
            }
            Repr::Pool(chars) => chars.size_hint(),
        }
    }
}

impl FusedIterator for MappedChar {}
